[workspace]
resolver = "2"
members = [
    "aeronet",
    "aeronet_derive",
    "aeronet_steam",
    "aeronet_channel",
    "aeronet_wt_native",
    "aeronet_wt_wasm",
]

[workspace.package]
version = "0.5.0"
edition = "2021"
rust-version = "1.75.0"
authors = ["aecsocket <aecsocket@tutanota.com>"]
repository = "https://github.com/aecsocket/aeronet"
keywords = ["gamedev", "network", "bevy"]
categories = ["game-development", "network-programming"]
license = "MIT OR Apache-2.0"

[workspace.lints.rust]
# missing_docs = "warn"
# unused_crate_dependencies = "warn"

[workspace.lints.clippy]
all = "warn"
pedantic = "warn"
module_name_repetitions = "allow"
similar_names = "allow"

[workspace.dependencies]
aeronet = { version = "0.5.0", path = "aeronet" }
aeronet_derive = { version = "0.5.0", path = "aeronet_derive" }
aeronet_example = { version = "0.5.0", path = "aeronet_example" }

derivative = "2.2.0"
tracing = "0.1.40"
thiserror = "1.0.56"
either = "1.9.0"
slotmap = "1.0.7"
ahash = "0.8.7"
anyhow = "1.0.79"
rand = "0.8.5"
rand_distr = "0.4.3"
bitcode = "0.5.0"

proc-macro2 = "1.0.76"
syn = "2.0.48"
quote = "1.0.35"
const_format = "0.2.32"

tokio = { version = "1.35.1", default-features = false }
futures = "0.3.30"
crossbeam-channel = "0.5.11"

bevy_ecs = { version = "0.12.1", default-features = false }
bevy_app = { version = "0.12.1", default-features = false }
bevy = "0.12.1"
bevy_egui = "0.24.0"

wtransport = "0.1.10"

wasm-bindgen = "0.2.90"
wasm-bindgen-futures = "0.4.40"
js-sys = "0.3.67"
web-sys = "0.3.67"

base64 = "0.21.7"
rcgen = "0.12.0"
ring = "0.17.7"
time = "0.3.31"

steamworks = { git = "https://github.com/Noxime/steamworks-rs" }
